version: '2'

services:
  couchdb0:
    image: hyperledger/fabric-couchdb
    container_name: couchdb0
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    ports:
      - 6984:5984

  couchdb1:
    image: hyperledger/fabric-couchdb
    container_name: couchdb1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    ports:
      - 7984:5984

  couchdb2:
    image: hyperledger/fabric-couchdb
    container_name: couchdb2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    ports:
      - 8984:5984

  couchdb3:
    image: hyperledger/fabric-couchdb
    container_name: couchdb3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    ports:
      - 9984:5984

  couchdb4:
    image: hyperledger/fabric-couchdb
    container_name: couchdb4
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    ports:
      - 10984:5984

  couchdb5:
    image: hyperledger/fabric-couchdb
    container_name: couchdb5
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456
    ports:
      - 11984:5984


  peer0.org1.SCRT.com:
    container_name: peer0.org1.SCRT.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer0.org1.SCRT.com
      - CORE_PEER_ADDRESS=peer0.org1.SCRT.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.SCRT.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.SCRT.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer0.org1.SCRT.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer0.org1.SCRT.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org1.SCRT.com:
    container_name: peer1.org1.SCRT.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer1.org1.SCRT.com
      - CORE_PEER_ADDRESS=peer1.org1.SCRT.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org1.SCRT.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.SCRT.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer1.org1.SCRT.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer1.org1.SCRT.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8052:7052
      - 8053:7053


  peer2.org1.SCRT.com:
    container_name: peer2.org1.SCRT.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer2.org1.SCRT.com
      - CORE_PEER_ADDRESS=peer2.org1.SCRT.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer2.org1.SCRT.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.SCRT.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer2.org1.SCRT.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer2.org1.SCRT.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053

  peer3.org1.SCRT.com:
    container_name: peer3.org1.SCRT.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer3.org1.SCRT.com
      - CORE_PEER_ADDRESS=peer3.org1.SCRT.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer3.org1.SCRT.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.SCRT.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer3.org1.SCRT.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer3.org1.SCRT.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10052:7052
      - 10053:7053

  peer4.org1.SCRT.com:
    container_name: peer4.org1.SCRT.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer4.org1.SCRT.com
      - CORE_PEER_ADDRESS=peer4.org1.SCRT.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer4.org1.SCRT.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer4.org1.SCRT.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer4.org1.SCRT.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer4.org1.SCRT.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11052:7052
      - 11053:7053

  peer5.org1.SCRT.com:
    container_name: peer5.org1.SCRT.com
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
      - CORE_PEER_ID=peer5.org1.SCRT.com
      - CORE_PEER_ADDRESS=peer5.org1.SCRT.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer5.org1.SCRT.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer5.org1.SCRT.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer5.org1.SCRT.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.SCRT.com/peers/peer5.org1.SCRT.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12052:7052
      - 12053:7053

